/* HORMUZ WAR — complete battlefield localization layer
   Keeps game logic untouched and translates dynamic HUD, target reports,
   weapon cards, notifications and end-of-battle messages. */
(function(){
  const EXTRA={
    en:{turn:'TURN',planning:'PLANNING',victory:'VICTORY',defeat:'DEFEAT',draw:'DRAW',hp:'HP',destroyed:'DESTROYED',missed:'MISS',hit:'HIT',damage:'DAMAGE',repaired:'REPAIRED',shielded:'SHIELDED',jammed:'JAMMED',ready:'READY',enemyTurn:'ENEMY TURN',yourTurn:'YOUR TURN',target:'TARGET',friendly:'FRIENDLY',enemy:'ENEMY',selectTarget:'SELECT TARGET',noAmmo:'NO AMMO',systemUsed:'SYSTEM USED',attackFailed:'ATTACK FAILED',battleWon:'BATTLE WON',battleLost:'BATTLE LOST',continueBattle:'CONTINUE',restart:'RESTART'},
    fa:{turn:'نوبت',planning:'آماده‌سازی',victory:'پیروزی',defeat:'شکست',draw:'مساوی',hp:'سلامتی',destroyed:'منهدم شد',missed:'خطا',hit:'اصابت',damage:'آسیب',repaired:'تعمیر شد',shielded:'محافظت شد',jammed:'مختل شد',ready:'آماده',enemyTurn:'نوبت دشمن',yourTurn:'نوبت شما',target:'هدف',friendly:'خودی',enemy:'دشمن',selectTarget:'انتخاب هدف',noAmmo:'مهمات تمام شده',systemUsed:'سیستم استفاده شد',attackFailed:'حمله ناموفق',battleWon:'نبرد با پیروزی تمام شد',battleLost:'نبرد با شکست تمام شد',continueBattle:'ادامه',restart:'شروع دوباره'},
    ar:{turn:'الدور',planning:'التخطيط',victory:'النصر',defeat:'الهزيمة',draw:'تعادل',hp:'الصحة',destroyed:'دُمّرت',missed:'خطأ',hit:'إصابة',damage:'الضرر',repaired:'تم الإصلاح',shielded:'محمي',jammed:'تم التشويش',ready:'جاهز',enemyTurn:'دور العدو',yourTurn:'دورك',target:'الهدف',friendly:'صديق',enemy:'عدو',selectTarget:'اختر الهدف',noAmmo:'لا توجد ذخيرة',systemUsed:'تم استخدام النظام',attackFailed:'فشل الهجوم',battleWon:'انتهت المعركة بالنصر',battleLost:'انتهت المعركة بالهزيمة',continueBattle:'متابعة',restart:'إعادة التشغيل'},
    tr:{turn:'TUR',planning:'PLANLAMA',victory:'ZAFER',defeat:'YENİLGİ',draw:'BERABERE',hp:'CAN',destroyed:'İMHA EDİLDİ',missed:'ISKA',hit:'İSABET',damage:'HASAR',repaired:'ONARILDI',shielded:'KORUMALI',jammed:'KARARTILDI',ready:'HAZIR',enemyTurn:'DÜŞMAN TURU',yourTurn:'SİZİN TURUNUZ',target:'HEDEF',friendly:'DOST',enemy:'DÜŞMAN',selectTarget:'HEDEF SEÇ',noAmmo:'MÜHİMMAT YOK',systemUsed:'SİSTEM KULLANILDI',attackFailed:'SALDIRI BAŞARISIZ',battleWon:'SAVAŞ KAZANILDI',battleLost:'SAVAŞ KAYBEDİLDİ',continueBattle:'DEVAM',restart:'YENİDEN BAŞLAT'},
    ja:{turn:'ターン',planning:'作戦準備',victory:'勝利',defeat:'敗北',draw:'引き分け',hp:'耐久',destroyed:'撃破',missed:'外れ',hit:'命中',damage:'ダメージ',repaired:'修理完了',shielded:'シールド展開',jammed:'妨害中',ready:'準備完了',enemyTurn:'敵ターン',yourTurn:'自分のターン',target:'目標',friendly:'味方',enemy:'敵',selectTarget:'目標を選択',noAmmo:'弾薬切れ',systemUsed:'システム使用',attackFailed:'攻撃失敗',battleWon:'戦闘勝利',battleLost:'戦闘敗北',continueBattle:'続行',restart:'再開'},
    zh:{turn:'回合',planning:'作战准备',victory:'胜利',defeat:'失败',draw:'平局',hp:'生命值',destroyed:'已摧毁',missed:'未命中',hit:'命中',damage:'伤害',repaired:'已修复',shielded:'护盾启动',jammed:'受到干扰',ready:'准备就绪',enemyTurn:'敌方回合',yourTurn:'我方回合',target:'目标',friendly:'友军',enemy:'敌军',selectTarget:'选择目标',noAmmo:'弹药耗尽',systemUsed:'系统已使用',attackFailed:'攻击失败',battleWon:'战斗胜利',battleLost:'战斗失败',continueBattle:'继续',restart:'重新开始'},
    es:{turn:'TURNO',planning:'PLANIFICACIÓN',victory:'VICTORIA',defeat:'DERROTA',draw:'EMPATE',hp:'SALUD',destroyed:'DESTRUIDO',missed:'FALLO',hit:'IMPACTO',damage:'DAÑO',repaired:'REPARADO',shielded:'PROTEGIDO',jammed:'INTERFERIDO',ready:'LISTO',enemyTurn:'TURNO ENEMIGO',yourTurn:'TU TURNO',target:'OBJETIVO',friendly:'ALIADO',enemy:'ENEMIGO',selectTarget:'SELECCIONAR OBJETIVO',noAmmo:'SIN MUNICIÓN',systemUsed:'SISTEMA USADO',attackFailed:'ATAQUE FALLIDO',battleWon:'BATALLA GANADA',battleLost:'BATALLA PERDIDA',continueBattle:'CONTINUAR',restart:'REINICIAR'},
    fr:{turn:'TOUR',planning:'PLANIFICATION',victory:'VICTOIRE',defeat:'DÉFAITE',draw:'ÉGALITÉ',hp:'PV',destroyed:'DÉTRUIT',missed:'ÉCHEC',hit:'IMPACT',damage:'DÉGÂTS',repaired:'RÉPARÉ',shielded:'PROTÉGÉ',jammed:'BROUILLÉ',ready:'PRÊT',enemyTurn:'TOUR ENNEMI',yourTurn:'VOTRE TOUR',target:'CIBLE',friendly:'ALLIÉ',enemy:'ENNEMI',selectTarget:'CHOISIR LA CIBLE',noAmmo:'PLUS DE MUNITIONS',systemUsed:'SYSTÈME UTILISÉ',attackFailed:'ATTAQUE ÉCHOUÉE',battleWon:'BATAILLE GAGNÉE',battleLost:'BATAILLE PERDUE',continueBattle:'CONTINUER',restart:'RECOMMENCER'},
    de:{turn:'RUNDE',planning:'PLANUNG',victory:'SIEG',defeat:'NIEDERLAGE',draw:'UNENTSCHIEDEN',hp:'LP',destroyed:'ZERSTÖRT',missed:'FEHLSCHLAG',hit:'TREFFER',damage:'SCHADEN',repaired:'REPARIERT',shielded:'GESCHÜTZT',jammed:'GESTÖRT',ready:'BEREIT',enemyTurn:'FEINDLICHE RUNDE',yourTurn:'DEINE RUNDE',target:'ZIEL',friendly:'VERBÜNDET',enemy:'FEIND',selectTarget:'ZIEL WÄHLEN',noAmmo:'KEINE MUNITION',systemUsed:'SYSTEM VERWENDET',attackFailed:'ANGRIFF FEHLGESCHLAGEN',battleWon:'KAMPF GEWONNEN',battleLost:'KAMPF VERLOREN',continueBattle:'WEITER',restart:'NEUSTART'},
    ru:{turn:'ХОД',planning:'ПЛАНИРОВАНИЕ',victory:'ПОБЕДА',defeat:'ПОРАЖЕНИЕ',draw:'НИЧЬЯ',hp:'ОЗ',destroyed:'УНИЧТОЖЕН',missed:'ПРОМАХ',hit:'ПОПАДАНИЕ',damage:'УРОН',repaired:'ОТРЕМОНТИРОВАНО',shielded:'ЗАЩИЩЕНО',jammed:'ПОДАВЛЕНО',ready:'ГОТОВО',enemyTurn:'ХОД ВРАГА',yourTurn:'ВАШ ХОД',target:'ЦЕЛЬ',friendly:'СОЮЗНИК',enemy:'ВРАГ',selectTarget:'ВЫБЕРИТЕ ЦЕЛЬ',noAmmo:'НЕТ БОЕПРИПАСОВ',systemUsed:'СИСТЕМА ИСПОЛЬЗОВАНА',attackFailed:'АТАКА НЕ УДАЛАСЬ',battleWon:'БОЙ ВЫИГРАН',battleLost:'БОЙ ПРОИГРАН',continueBattle:'ПРОДОЛЖИТЬ',restart:'ЗАНОВО'}
  };
  const systemNames={
    en:{'Basic Missile':'Basic Missile','Recon Drone':'Recon Drone','Basic Interceptor':'Basic Interceptor','Heavy Missile':'Heavy Missile','Fast Attack Boat':'Fast Attack Boat','Precision Missile':'Precision Missile','Long Range Missile':'Long Range Missile','Rapid Defense Missile':'Rapid Defense Missile','Shockwave':'Shockwave','Emergency Shield':'Emergency Shield','Jammer':'Jammer','Repair System':'Repair System'},
    fa:{'Basic Missile':'موشک پایه','Recon Drone':'پهپاد شناسایی','Basic Interceptor':'رهگیر پایه','Heavy Missile':'موشک سنگین','Fast Attack Boat':'قایق تهاجمی سریع','Precision Missile':'موشک دقیق','Long Range Missile':'موشک دوربرد','Rapid Defense Missile':'موشک دفاع سریع','Shockwave':'موج شوک','Emergency Shield':'سپر اضطراری','Jammer':'سامانه اخلالگر','Repair System':'سامانه تعمیر'},
    ar:{'Basic Missile':'صاروخ أساسي','Recon Drone':'طائرة استطلاع مسيرة','Basic Interceptor':'اعتراض أساسي','Heavy Missile':'صاروخ ثقيل','Fast Attack Boat':'زورق هجومي سريع','Precision Missile':'صاروخ دقيق','Long Range Missile':'صاروخ بعيد المدى','Rapid Defense Missile':'صاروخ دفاع سريع','Shockwave':'موجة صدمة','Emergency Shield':'درع طوارئ','Jammer':'نظام تشويش','Repair System':'نظام إصلاح'},
    tr:{'Basic Missile':'Temel Füze','Recon Drone':'Keşif İHA','Basic Interceptor':'Temel Önleyici','Heavy Missile':'Ağır Füze','Fast Attack Boat':'Hızlı Saldırı Botu','Precision Missile':'Hassas Füze','Long Range Missile':'Uzun Menzilli Füze','Rapid Defense Missile':'Hızlı Savunma Füzesi','Shockwave':'Şok Dalgası','Emergency Shield':'Acil Kalkan','Jammer':'Karıştırıcı','Repair System':'Onarım Sistemi'},
    ja:{'Basic Missile':'基本ミサイル','Recon Drone':'偵察ドローン','Basic Interceptor':'基本迎撃システム','Heavy Missile':'重ミサイル','Fast Attack Boat':'高速攻撃艇','Precision Missile':'精密ミサイル','Long Range Missile':'長距離ミサイル','Rapid Defense Missile':'高速防衛ミサイル','Shockwave':'衝撃波','Emergency Shield':'緊急シールド','Jammer':'ジャマー','Repair System':'修理システム'},
    zh:{'Basic Missile':'基础导弹','Recon Drone':'侦察无人机','Basic Interceptor':'基础拦截器','Heavy Missile':'重型导弹','Fast Attack Boat':'快速攻击艇','Precision Missile':'精确导弹','Long Range Missile':'远程导弹','Rapid Defense Missile':'快速防御导弹','Shockwave':'冲击波','Emergency Shield':'紧急护盾','Jammer':'干扰器','Repair System':'维修系统'},
    es:{'Basic Missile':'Misil básico','Recon Drone':'Dron de reconocimiento','Basic Interceptor':'Interceptor básico','Heavy Missile':'Misil pesado','Fast Attack Boat':'Lancha de ataque rápida','Precision Missile':'Misil de precisión','Long Range Missile':'Misil de largo alcance','Rapid Defense Missile':'Misil de defensa rápida','Shockwave':'Onda de choque','Emergency Shield':'Escudo de emergencia','Jammer':'Interferidor','Repair System':'Sistema de reparación'},
    fr:{'Basic Missile':'Missile standard','Recon Drone':'Drone de reconnaissance','Basic Interceptor':'Intercepteur standard','Heavy Missile':'Missile lourd','Fast Attack Boat':'Vedette d’attaque rapide','Precision Missile':'Missile de précision','Long Range Missile':'Missile longue portée','Rapid Defense Missile':'Missile de défense rapide','Shockwave':'Onde de choc','Emergency Shield':'Bouclier d’urgence','Jammer':'Brouilleur','Repair System':'Système de réparation'},
    de:{'Basic Missile':'Standardrakete','Recon Drone':'Aufklärungsdrohne','Basic Interceptor':'Standard-Abfangsystem','Heavy Missile':'Schwere Rakete','Fast Attack Boat':'Schnelles Angriffsboot','Precision Missile':'Präzisionsrakete','Long Range Missile':'Langstreckenrakete','Rapid Defense Missile':'Schnelle Abwehrrakete','Shockwave':'Schockwelle','Emergency Shield':'Notfallschild','Jammer':'Störsender','Repair System':'Reparatursystem'},
    ru:{'Basic Missile':'Базовая ракета','Recon Drone':'Разведывательный дрон','Basic Interceptor':'Базовый перехватчик','Heavy Missile':'Тяжёлая ракета','Fast Attack Boat':'Быстрый ударный катер','Precision Missile':'Точная ракета','Long Range Missile':'Дальнобойная ракета','Rapid Defense Missile':'Быстрая оборонительная ракета','Shockwave':'Ударная волна','Emergency Shield':'Аварийный щит','Jammer':'Глушитель','Repair System':'Ремонтная система'}
  };
  function lang(){return localStorage.getItem('hw-language')||localStorage.getItem('hormuz-language')||'en'}
  function tr(key){const l=lang();return (EXTRA[l]||EXTRA.en)[key]||EXTRA.en[key]||key}
  function translateText(s){if(!s)return s;let out=s;Object.keys(systemNames.en).forEach(k=>{const v=(systemNames[lang()]||systemNames.en)[k];out=out.split(k).join(v)});return out}
  function scan(root=document){root.querySelectorAll('#targetInfo,#selectedSystemInfo,#systemInfo,#toast,.battle-loadout,#modalBody').forEach(el=>{if(el.dataset.hwI18n)return; const raw=el.innerText||''; if(raw){el.innerText=translateText(raw); el.dataset.hwI18n='1'}})}
  function update(){
    document.documentElement.dir=(['fa','ar'].includes(lang())?'rtl':'ltr');
    const phase=document.getElementById('phaseText'); if(phase && ['PLANNING','YOUR TURN','ENEMY TURN'].includes(phase.textContent.trim())) phase.textContent=tr(phase.textContent.trim().toLowerCase().replace(/ /g,''));
    const hint=document.getElementById('actionHint'); if(hint) hint.textContent=translateText(hint.textContent);
    scan();
  }
  window.HW_BATTLE_I18N={update,tr,translateText};
  const obs=new MutationObserver(()=>{scan();});
  window.addEventListener('DOMContentLoaded',()=>{obs.observe(document.body,{childList:true,subtree:true,characterData:true});update();});
  window.addEventListener('hw-language-changed',update);
  setInterval(update,800);
})();
