import {FACTIONS,UNITS,BUILDINGS,STRATEGIC,ROUTES,DIFFICULTY} from "./v1-config.js";
const $=id=>document.getElementById(id);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
let G=null;
function factionUnits(side){return UNITS[side];}
function unitDef(side,id){return factionUnits(side).find(u=>u.id===id)}
function other(side){return side==="north"?"south":"north"}
function createGame(player,diff){
 const W=2600,H=1700;
 G={W,H,player,enemy:other(player),diff,war:{north:1800,south:1800},supply:{north:42,south:42},supplyMax:{north:70,south:70},power:{north:"ONLINE",south:"ONLINE"},bp:{north:0,south:0},weather:"CLEAR",time:0,selected:null,camera:{x:0,y:0},units:[],buildings:[],points:STRATEGIC.map((s,i)=>({...s,owner:null,x:[1300,950,1650][i],y:850})),ships:[],stats:{north:{lost:0,destroyed:0,protected:0,earned:0},south:{lost:0,destroyed:0,protected:0,earned:0}},lastAI:0,paused:false,over:null,alert:null,groups:{},controlGroup:0};
 const slots={north:[{x:300,y:230},{x:600,y:230},{x:900,y:250},{x:300,y:430},{x:600,y:430},{x:900,y:430}],south:[{x:1700,y:1270},{x:2000,y:1270},{x:2300,y:1270},{x:1700,y:1450},{x:2000,y:1450},{x:2300,y:1450}]};
 for(const side of ["north","south"]){
  const s=slots[side]; G.buildings.push({side,type:"command",x:side==="north"?600:2000,y:side==="north"?320:1380,hp:3000,max:3000});
  ["power","supply","production","radar","airdef"].forEach((type,i)=>G.buildings.push({side,type,x:s[i].x,y:s[i].y,hp:BUILDINGS.find(b=>b.id===type).hp,max:BUILDINGS.find(b=>b.id===type).hp}));
  const ids=side==="north"?["patrol_ship","fast_attack_boat","recon_drone"]:["frigate","recon_aircraft"];
  ids.forEach((id,i)=>spawn(side,id,side==="north"?500+i*180:1900+i*180,side==="north"?550:1150));
 }
 for(const r of ROUTES) G.ships.push({route:r.id,side:r.id==="north"?"north":r.id==="south"?"south":Math.random()<.5?"north":"south",x:r.id==="north"?180:1300,y:r.id==="north"?850:r.id==="south"?850:850,progress:0,hp:500,type:r.type,identified:false,neutral:false});
 render(); updateHUD(); requestAnimationFrame(loop); return G;
}
function spawn(side,id,x,y){const d=unitDef(side,id);if(!d||G.supply[side]+d.supply>G.supplyMax[side])return null;const u={uid:crypto.randomUUID(),side,id,x,y,hp:d.hp,max:d.hp,moving:null,retreat:false,burst:false,repairCd:0};G.units.push(u);G.supply[side]+=d.supply;return u}
function alert(msg,x,y){G.alert={msg,x,y,t:2};$("alert").textContent=msg;$("alert").classList.add("show");setTimeout(()=>{if($("alert"))$("alert").classList.remove("show")},1600)}
function canSee(side,u){const radar=G.buildings.some(b=>b.side===side&&b.type==="radar"&&b.hp>0), range=radar?520:330;return G.units.filter(a=>a.side===side&&a.hp>0).some(a=>dist(a,u)<(unitDef(side,a.id)?.range||200)*.65)+G.points.some(p=>p.owner===side&&dist(p,u)<300)}
function effective(att,def){const aid=att.id,did=def.id;if((aid.includes("missile")||aid==="combat_drone")&&(did==="destroyer"||did==="frigate"))return 1.25;if(aid==="fast_attack_boat"&&(did.includes("ship")||did==="recon_aircraft"||did==="recon_drone"))return 1.25;if((aid==="combat_aircraft"||aid==="legacy_fighter")&&(did.includes("aircraft")||did.includes("drone")))return 1.25;if(did==="airdef"||def.id==="airdef")return .6;return 1}
function attack(att,def){if(!att||!def||att.hp<=0||def.hp<=0||att.side===def.side)return false;const a=unitDef(att.side,att.id);if(dist(att,def)>a.range)return false;let dmg=Math.round(a.attack*effective(att,def)*(att.burst?1.15:1));if(def.shield)dmg=Math.round(dmg*.6);def.hp-=dmg;G.bp[att.side]+=1;if(dmg>0)showHit(def.x,def.y);if(def.hp<=0){def.hp=0;G.stats[att.side].destroyed++;G.stats[def.side].lost++;G.supply[def.side]=Math.max(0,G.supply[def.side]-(a.supply||2));alert((def.id==="command"?"COMMAND CENTER DESTROYED":unitDef(def.side,def.id)?.name+" DESTROYED"));checkEnd()}return true}
function move(u,x,y){const d=unitDef(u.side,u.id);if(!d||d.speed===0)return;u.moving={x:clamp(x,60,G.W-60),y:clamp(y,60,G.H-60)}}
function select(u){G.selected=u;if(u){G.camera.x=clamp(u.x-innerWidth*.35,0,G.W-innerWidth);G.camera.y=clamp(u.y-(innerHeight-62)*.45,0,G.H-(innerHeight-62))}renderPanels()}
function produce(side,id){const d=unitDef(side,id),cost=d?.cost||0;if(!d)return;if(G.war[side]<cost){alert("NOT ENOUGH WAR FUNDS");return}if(G.supply[side]+d.supply>G.supplyMax[side]){alert("NOT ENOUGH SUPPLY CAPACITY");return}G.war[side]-=cost;setTimeout(()=>{const y=side==="north"?540:1160;spawn(side,id,side==="north"?600:2000,y);alert(d.name+" READY")},d.time*250)}
function support(side,type){const cost=type==="repair"?2:1;if(G.bp[side]<cost){alert("NOT ENOUGH BATTLE POINTS");return}G.bp[side]-=cost;if(type==="repair"){if(G.selected&&G.selected.side===side)G.selected.hp=clamp(G.selected.hp+G.selected.max*.2,0,G.selected.max)}else{for(const u of G.units.filter(x=>x.side===other(side)&&x.hp>0)){if(dist(u,G.selected||{x:G.W/2,y:G.H/2})<700)u.revealed=3}}}
function damageBuilding(b,dmg,side){b.hp-=dmg;G.bp[side]++;if(b.hp<=0){b.hp=0;if(b.type==="supply")G.supplyMax[b.side]=Math.max(40,G.supplyMax[b.side]-25);if(b.type==="power")G.power[b.side]="OFFLINE";if(b.type==="radar")alert("RADAR DESTROYED");if(b.type==="command")checkEnd()}}
function checkEnd(){for(const side of ["north","south"]){const c=G.buildings.find(b=>b.side===side&&b.type==="command");if(!c||c.hp<=0){G.over=G.player===other(side)?"victory":"defeat";showSummary();}}}
function trade(dt){for(const s of G.ships){s.progress+=dt*(G.points[1].owner===s.side?1.25:1)*.012;if(s.progress>=1){if(s.type==="TANKER"){G.war[s.side]+=250;G.stats[s.side].earned+=250}if(s.type==="LOGISTICS")G.supply[s.side]=clamp(G.supply[s.side]+12,0,G.supplyMax[s.side]);s.progress=0;G.stats[s.side].protected++;}}}
function strategic(){for(const p of G.points){const near={north:0,south:0};for(const u of G.units)if(u.hp>0&&dist(u,p)<180)near[u.side]++;p.owner=near.north===near.south?p.owner:(near.north>near.south?"north":"south");if(p.owner)G.bp[p.owner]+=.01}}
function ai(dt){if(G.player==="")return;G.lastAI+=dt;const D=DIFFICULTY[G.diff];if(G.lastAI<D.interval)return;G.lastAI=0;const s=G.enemy;if(Math.random()<.6*D.production){const affordable=factionUnits(s).filter(d=>G.war[s]>=d.cost&&G.supply[s]+d.supply<=G.supplyMax[s]);if(affordable.length){const d=affordable[Math.floor(Math.random()*affordable.length)];produce(s,d.id)}}const visible=G.units.filter(u=>u.side===G.player&&u.hp>0&&canSee(s,u));if(visible.length){const target=visible.sort((a,b)=>b.hp-a.hp)[0], own=G.units.filter(u=>u.side===s&&u.hp>0&&unitDef(s,u.id).attack>0);for(const u of own.slice(0,Math.ceil((D.focus||1)*2))){if(dist(u,target)<=unitDef(s,u.id).range)attack(u,target);else move(u,target.x+(Math.random()-.5)*120,target.y+(Math.random()-.5)*120)}}else{const c=G.buildings.find(b=>b.side===G.player&&b.type==="command"&&b.hp>0);const own=G.units.filter(u=>u.side===s&&u.hp>0&&unitDef(s,u.id).attack>0);for(const u of own.slice(0,Math.ceil(D.focus*2))){if(c&&dist(u,c)<=unitDef(s,u.id).range)attackBuilding(u,c);else if(c)move(u,c.x,c.y)}}}
function update(dt){if(G.paused||G.over)return;G.time+=dt;for(const u of G.units){if(u.hp<=0)continue;if(u.moving){const d=unitDef(u.side,u.id),dx=u.moving.x-u.x,dy=u.moving.y-u.y,l=Math.hypot(dx,dy);if(l<3)u.moving=null;else{const v=d.speed*18*dt;u.x+=dx/l*Math.min(v,l);u.y+=dy/l*Math.min(v,l)}}if(u.repairCd>0)u.repairCd-=dt}trade(dt);strategic();ai(dt);if(Math.floor(G.time)%10===0){G.war.north+=.15;G.war.south+=.15}updateHUD();renderPanels()}
function loop(t){if(!G)return;const last=G._t||t;const dt=Math.min(.1,(t-last)/1000);G._t=t;update(dt);draw();requestAnimationFrame(loop)}
function worldToScreen(x,y){return{x:x-G.camera.x,y:y-G.camera.y}}
function draw(){const c=$("map");if(!c)return;const ctx=c.getContext("2d");c.width=$("world").clientWidth;c.height=$("world").clientHeight;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle="#0b3038";ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle="#0b242b";ctx.fillRect(0,0,c.width,G.H*.45);ctx.fillStyle="#102a24";for(const island of [{x:800,y:650,w:250,h:130},{x:1200,y:930,w:280,h:150},{x:1750,y:600,w:260,h:120}]){const p=worldToScreen(island.x,island.y);ctx.beginPath();ctx.ellipse(p.x,p.y,island.w/2,island.h/2,0,0,7);ctx.fill()}for(const r of ROUTES){ctx.strokeStyle="#7ca7ad33";ctx.setLineDash([12,10]);ctx.beginPath();ctx.moveTo(worldToScreen(80,850).x,worldToScreen(80,850).y);ctx.lineTo(worldToScreen(G.W-80,850).x,worldToScreen(G.W-80,850).y);ctx.stroke();ctx.setLineDash([])}for(const p of G.points){const q=worldToScreen(p.x,p.y);ctx.beginPath();ctx.arc(q.x,q.y,26,0,7);ctx.fillStyle=p.owner==="north"?"#d94b5266":p.owner==="south"?"#4f8fe866":"#d6c56a55";ctx.fill();ctx.strokeStyle="#d6c56a";ctx.stroke();ctx.fillStyle="#fff";ctx.font="11px Arial";ctx.fillText(p.name.split(" ")[0],q.x-20,q.y+42)}for(const b of G.buildings){const q=worldToScreen(b.x,b.y);ctx.fillStyle=b.side==="north"?"#7d252c":"#214c82";ctx.fillRect(q.x-32,q.y-24,64,48);ctx.strokeStyle=b.hp<b.max*.35?"#e7b85c":b.side==="north"?"#e8666b":"#70a9ee";ctx.strokeRect(q.x-32,q.y-24,64,48);ctx.fillStyle="#e9f0f2";ctx.font="9px Arial";ctx.textAlign="center";ctx.fillText(b.type.toUpperCase(),q.x,q.y+3);ctx.textAlign="left"}for(const u of G.units){if(u.hp<=0)continue;const visible=u.side===G.player||canSee(G.player,u)||u.revealed>0;if(u.revealed>0)u.revealed=Math.max(0,u.revealed-.016);if(!visible)continue;const q=worldToScreen(u.x,u.y),d=unitDef(u.side,u.id);ctx.beginPath();ctx.arc(q.x,q.y,18,0,7);ctx.fillStyle=u.side==="north"?"#d94b52":"#4f8fe8";ctx.fill();if(G.selected===u){ctx.strokeStyle="#ffe28a";ctx.lineWidth=3;ctx.stroke()}ctx.fillStyle="#061015";ctx.font="bold 11px Arial";ctx.textAlign="center";ctx.fillText(d.name[0],q.x,q.y+4);ctx.fillStyle="#162126";ctx.fillRect(q.x-22,q.y-30,44,4);ctx.fillStyle="#72d38a";ctx.fillRect(q.x-22,q.y-30,44*(u.hp/u.max),4);ctx.textAlign="left"}}
function renderPanels(){const p=G.selected, box=$("selection");if(!p){box.innerHTML="<div class='selectedInfo'>Select a unit or building.</div>";return}if(p.type&&p.hp!==undefined){box.innerHTML=`<div><b>${p.type.toUpperCase()}</b><br>HP ${Math.ceil(p.hp)} / ${p.max}<br>Side: ${p.side.toUpperCase()}<div class="cmds"><button data-cmd="attack">ATTACK</button></div></div>`;box.querySelector("button").onclick=()=>{const u=G.units.find(u=>u.side===G.player&&u.hp>0&&dist(u,p)<=unitDef(u.side,u.id).range);if(u)attackBuilding(u,p)};return}const d=unitDef(p.side,p.id);if(d){box.innerHTML=`<div><b class="${p.side==="north"?"red":"blue"}">${d.name}</b><br>HP ${Math.ceil(p.hp)} / ${p.max}<br>Attack ${d.attack} • Range ${d.range} • Speed ${d.speed}<br>Role: ${d.role}<br>Strong: ${d.strong}<br>Weak: ${d.weak}<div class="cmds"><button data-cmd="move">MOVE</button><button data-cmd="attack">ATTACK</button><button data-cmd="stop">STOP</button><button data-cmd="retreat">RETREAT</button><button data-cmd="special">SPECIAL</button></div></div>`;box.querySelectorAll("button").forEach(b=>b.onclick=()=>command(b.dataset.cmd))}updateProduction()}
function updateProduction(){const el=$("production");if(!el||!G)return;const ds=factionUnits(G.player);el.innerHTML=ds.map(d=>`<div class="prod"><span>${d.name}<small> ${d.cost} WF / ${d.supply} S</small></span><button data-id="${d.id}" ${G.war[G.player]<d.cost||G.supply[G.player]+d.supply>G.supplyMax[G.player]?"disabled":""}>BUILD</button></div>`).join("");el.querySelectorAll("button").forEach(b=>b.onclick=()=>produce(G.player,b.dataset.id))}
function command(cmd){const u=G.selected;if(!u||u.side!==G.player)return;if(cmd==="move"){const x=G.camera.x+innerWidth*.4,y=G.camera.y+(innerHeight-62)*.45;move(u,x,y)}if(cmd==="stop")u.moving=null;if(cmd==="retreat"){u.retreat=true;move(u,G.player==="north"?300:G.W-300,G.player==="north"?250:1450)}if(cmd==="special"){if(u.id==="fast_attack_boat"){u.burst=true;move(u,u.x+(G.player==="north"?300:-300),u.y)}if(u.id==="support_aircraft"&&u.repairCd<=0){const ally=G.units.find(a=>a.side===G.player&&a!==u&&dist(a,u)<300);if(ally){ally.hp=clamp(ally.hp+ally.max*.15,0,ally.max);u.repairCd=12}}if(u.id==="recon_drone"||u.id==="recon_aircraft"){for(const e of G.units.filter(e=>e.side===G.enemy))e.revealed=8}}if(cmd==="attack"){const e=G.units.filter(e=>e.side===G.enemy&&e.hp>0&&canSee(G.player,e)).sort((a,b)=>dist(u,a)-dist(u,b))[0];const b=G.buildings.filter(b=>b.side===G.enemy&&b.hp>0&&b.type==="command").sort((a,b)=>dist(u,a)-dist(u,b))[0];if(e&&(!b||dist(u,e)<=dist(u,b)))attack(u,e);else if(b)attackBuilding(u,b);else alert("NO IDENTIFIED TARGET")}}
function attackBuilding(att,b){if(!att||!b||att.side===b.side||att.hp<=0||b.hp<=0)return false;const d=unitDef(att.side,att.id);if(!d||d.attack<=0||dist(att,b)>d.range)return false;const mult=(b.type==="airdef"&&att.id.includes("air"))?.6:1;damageBuilding(b,Math.round(d.attack*mult),att.side);showHit(b.x,b.y);return true}\nfunction showHit(x,y){const q=worldToScreen(x,y);const ctx=$("map").getContext("2d");ctx.save();ctx.strokeStyle="#ffd46b";ctx.beginPath();ctx.arc(q.x,q.y,30,0,7);ctx.stroke();ctx.restore()}
function drawMini(){const m=$("mini");if(!m||!G)return;const x=m.getContext("2d");x.clearRect(0,0,m.width,m.height);x.fillStyle="#0a252c";x.fillRect(0,0,m.width,m.height);for(const p of G.points){x.fillStyle=p.owner==="north"?"#d94b52":p.owner==="south"?"#4f8fe8":"#d6c56a";x.fillRect(p.x/G.W*m.width-3,p.y/G.H*m.height-3,6,6)}for(const u of G.units){if(u.hp<=0||!(u.side===G.player||canSee(G.player,u)||u.revealed>0))continue;x.fillStyle=u.side==="north"?"#d94b52":"#4f8fe8";x.fillRect(u.x/G.W*m.width-2,u.y/G.H*m.height-2,4,4)}x.strokeStyle="#fff8";x.strokeRect(G.camera.x/G.W*m.width,G.camera.y/G.H*m.height,($("world").clientWidth/G.W)*m.width,($("world").clientHeight/G.H)*m.height)}\nfunction updateHUD(){if(!G)return;$("funds").textContent=Math.floor(G.war[G.player]);$("supply").textContent=Math.floor(G.supply[G.player])+"/"+Math.floor(G.supplyMax[G.player]);$("power").textContent=G.power[G.player];$("bp").textContent=Math.floor(G.bp[G.player]);$("time").textContent=Math.floor(G.time/60)+":"+String(Math.floor(G.time%60)).padStart(2,"0");$("weather").textContent=G.weather}
function showSummary(){if(!$("summary"))return;$("summary").classList.remove("hidden");$("summaryTitle").textContent=G.over==="victory"?"VICTORY":"DEFEAT";$("summaryBody").innerHTML=`Battle Time: ${$("time").textContent}<br>Units Destroyed: ${G.stats[G.player].destroyed}<br>Units Lost: ${G.stats[G.player].lost}<br>WAR FUNDS Earned: ${Math.floor(G.stats[G.player].earned)}<br>Commercial Ships Protected: ${G.stats[G.player].protected}<br>Strategic Points Controlled: ${G.points.filter(p=>p.owner===G.player).length}`;G.paused=true}
function setup(){let player="north",diff="normal";$("start").onclick=()=>{$("menu").classList.remove("active");$("setup").classList.add("active")};document.querySelectorAll(".choice").forEach(x=>x.onclick=()=>{player=x.dataset.side;document.querySelectorAll(".choice").forEach(c=>c.classList.remove("selected"));x.classList.add("selected")});document.querySelectorAll(".diff").forEach(x=>x.onclick=()=>{diff=x.dataset.diff;document.querySelectorAll(".diff").forEach(c=>c.classList.remove("selected"));x.classList.add("selected")});$("begin").onclick=()=>{$("setup").classList.remove("active");$("game").classList.add("active");createGame(player,diff);resize()};$("pause").onclick=()=>{G.paused=!G.paused;$("pause").textContent=G.paused?"RESUME":"PAUSE"};$("mainmenu").onclick=()=>location.reload();$("supportRepair").onclick=()=>support(G.player,"repair");$("supportScan").onclick=()=>support(G.player,G.player==="north"?"scan":"scan");$("map").onclick=e=>{const r=$("map").getBoundingClientRect();const x=e.clientX-r.left+G.camera.x,y=e.clientY-r.top+G.camera.y;const u=G.units.find(u=>u.hp>0&&dist(u,{x,y})<28&&(u.side===G.player||canSee(G.player,u)||u.revealed>0));const b=G.buildings.find(b=>b.hp>0&&dist(b,{x,y})<55&&(b.side===G.player||canSee(G.player,{x:b.x,y:b.y})));if(u)select(u);else if(b){G.selected=b;renderPanels()}else if(G.selected&&G.selected.id)move(G.selected,x,y)};$("canvas").oncontextmenu=e=>{e.preventDefault();return false};window.addEventListener("keydown",e=>{if(!G)return;if(e.code==="Space")G.paused=!G.paused;if(e.key==="w")command("move");if(e.key==="a")command("attack");if(e.key==="s")command("stop");if(e.key==="r")command("retreat");if(e.key==="p")command("special")});window.addEventListener("resize",resize);window.addEventListener("mousemove",e=>{if(!G||G.paused)return;const edge=55;if(e.clientX<edge)G.camera.x=clamp(G.camera.x-8,0,G.W-innerWidth);if(e.clientX>innerWidth-edge)G.camera.x=clamp(G.camera.x+8,0,G.W-innerWidth);if(e.clientY<edge+62)G.camera.y=clamp(G.camera.y-8,0,G.H-(innerHeight-62));if(e.clientY>innerHeight-edge)G.camera.y=clamp(G.camera.y+8,0,G.H-(innerHeight-62))});setInterval(()=>{if(G&&!G.paused)renderPanels()},1000)}
function resize(){if(!G)return;G.camera.x=clamp(G.camera.x,0,Math.max(0,G.W-$("world").clientWidth));G.camera.y=clamp(G.camera.y,0,Math.max(0,G.H-$("world").clientHeight))}
setup();
